name: Deploy AI Daily to GitHub Pages

# 当有人推送内容到main分支时，或者通过API触发时，运行此工作流
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # 这允许手动在Actions标签页触发工作流
  repository_dispatch: # 允许通过API触发
    types: [deploy-daily]

# 设置GITHUB_TOKEN权限，允许写入仓库
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build with Jekyll
        run: bundle exec jekyll build --source . --destination _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
